# Generated by Django 5.1.5 on 2025-01-27 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_ofertas_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='page',
            field=models.CharField(default='COMPUTRABAJO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 1, 27, 11, 11, 22, 879924)),
        ),
    ]
