# Generated by Django 5.1.5 on 2025-01-24 14:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('fecha_registro', models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 1, 24, 14, 38, 49, 542272))),
                ('idCliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 7 y 15 dígitos y puede comenzar con "+"', regex='^\\+?\\d{7,15}$')])),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
