# Generated by Django 5.1.5 on 2025-03-11 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertasLaborales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enlace_oferta', models.TextField(unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OfertasLaborales',
                'verbose_name_plural': 'OfertasLaborales',
                'db_table': '"Specify"."OfertasLaborales"',
            },
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_candidato', models.TextField()),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('enlace_perfil', models.TextField(blank=True, null=True)),
                ('experiencia', models.JSONField(blank=True, null=True)),
                ('educacion', models.JSONField(blank=True, null=True)),
                ('curriculum', models.TextField(blank=True, null=True)),
                ('preguntas_preseleccion', models.JSONField(blank=True, null=True)),
                ('id_oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='ponde.ofertaslaborales')),
            ],
            options={
                'verbose_name': 'Candidatos',
                'verbose_name_plural': 'Candidatos',
                'db_table': '"Specify"."Candidatos"',
            },
        ),
    ]
