# Generated by Django 5.1.5 on 2025-01-26 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idOferta', models.AutoField(db_column='idOferta', primary_key=True, serialize=False)),
                ('titulo_oferta', models.TextField()),
                ('salario', models.CharField()),
                ('ubicacion', models.CharField()),
            ],
            options={
                'verbose_name': 'Ofertas',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Clientes', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 1, 26, 18, 6, 44, 972929)),
        ),
    ]
