# Generated by Django 5.1.5 on 2025-03-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponde', '0002_candidatos_url_oferta_candidato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experiencia_cargo', models.IntegerField(blank=True, null=True)),
                ('experiencia_herramienta', models.IntegerField(blank=True, null=True)),
                ('nivel_ingles', models.IntegerField(blank=True, null=True)),
                ('titulo_academico', models.IntegerField(blank=True, null=True)),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderado', to='ponde.candidatos')),
            ],
            options={
                'verbose_name': 'Ponderado',
                'verbose_name_plural': 'Ponderado',
                'db_table': '"Specify"."Ponderado"',
            },
        ),
    ]
