# Generated by Django 5.1.5 on 2025-03-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponde', '0003_ponderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponderado',
            name='id_candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderado', to='ponde.candidatos', unique=True),
        ),
    ]
