# Generated by Django 5.1.5 on 2025-01-28 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_ofertas_captured_at_alter_clientes_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 1, 28, 19, 13, 26, 434325)),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='page',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='salario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='ofertas',
            unique_together={('titulo_oferta', 'salario', 'ubicacion')},
        ),
    ]
